<a href="https://colab.research.google.com/github/MalePalma/Ingenias-Data/blob/main/Resoluci%C3%B3n_Notebook_5_Palma_Malena.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [2]:
#Ejercicio 1:Crear un arreglo de ceros de longitud 12#
import numpy as np
arreglo_ej_1= np.zeros(12)
print (arreglo_ej_1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
#Ejercicio 2: Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5#
import numpy as np
arreglo_ej_2= np.zeros (10)
arreglo_ej_2[4]=10
print (arreglo_ej_2)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [5]:
#Ejercicio 3: Crear un arreglo que tenga los números del 10 al 49#
import numpy as np
arreglo_ej_3= np.arange(10, 50)
print (arreglo_ej_3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [14]:
#Ejercicio 4: Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8#

import numpy as np
arreglo_ej_4= np.array (range(9)).reshape (3,3)
print (arreglo_ej_4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
#Ejercicio 5: Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza#
import numpy as np

#Arreglo de 100 numeros aleatorios#
arreglo_ej_5= np.random.random(100)
print("arreglo de 100 numero aleatorios:", arreglo_ej_5)

arreglo de 100 numero aleatorios: [0.31594366 0.34617008 0.52165141 0.44795682 0.38780008 0.93830126
 0.68658882 0.34363144 0.75253164 0.45124599 0.42185801 0.94417627
 0.20986679 0.24338456 0.31466808 0.50288051 0.84480935 0.8601651
 0.4415603  0.83422682 0.23655203 0.00127145 0.49222667 0.9166547
 0.99933338 0.88134495 0.08315538 0.30378576 0.56723337 0.83222337
 0.00890013 0.85579424 0.68334946 0.25384528 0.52091304 0.85723776
 0.15926325 0.28873737 0.36099923 0.75288584 0.02888347 0.07306358
 0.87162372 0.96093607 0.33379034 0.50101027 0.90685221 0.61381898
 0.84929319 0.27485594 0.35968212 0.66604604 0.85356216 0.37733105
 0.896966   0.91237721 0.32550735 0.46479498 0.88092808 0.85524169
 0.47782821 0.53191757 0.0654197  0.56312327 0.7433177  0.94060621
 0.92362543 0.19974715 0.57874438 0.69993156 0.0640107  0.78964986
 0.31733335 0.59484875 0.77642436 0.34018141 0.42813942 0.06670621
 0.17160176 0.63002125 0.81804626 0.79291182 0.91557236 0.27554869
 0.82939808 0.50832284 0.38970

In [21]:
#Media#
media=np.mean(arreglo_ej_5)
print ("Media:", media)

Media: 0.5313575199322991


In [22]:
#Varianza#
varianza= np.var(arreglo_ej_5)
print ("Varianza:", varianza)

varianza 0.08125553967420215


In [28]:
#Ejerciocio 6: Calcular la media de un arreglo usando np.sum#
import numpy as np
arreglo_ej_6= np.arange(1,61)
suma= np.sum(arreglo_ej_6)
cantidad=np.size(arreglo_ej_6)
media= suma/cantidad
print (media)

1830


In [33]:
#Ejercicio 7: Calcular la varianza de un arreglo usando np.sum y np.mean#
import numpy as np
arreglo_ej_7= np.arange(1,101)
cantidad= np.size (arreglo_ej_7)
media= np.mean (arreglo_ej_7)
varianza= np.sum((arreglo_ej_7 - media)**2)/cantidad
print (varianza)

833.25


In [35]:
# Ejercicio 8: Crear un array de números aleatorios usando np.random.randn.#
import numpy as np
arreglo_ej_8= np.random.randn (20)
print (arreglo_ej_8)

[ 0.85838679 -0.33881247 -0.49067362 -0.62188545 -0.51857471  1.13900356
 -0.89984865 -0.58036512  0.53366369  0.58889322 -0.58691963  0.09149777
 -0.48985092  1.36949692  1.24705861 -0.21391055 -0.53118699 -1.11247089
 -3.17514596  0.66615798]
